import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { readLocale, t } from '../i18n.js';
import { makeEnvelope, makeErrorEnvelope } from '../lib/json-output.js';
import type { OutputFormat } from '../lib/json-output.js';
import { normalizeSandboxConfig, runSandboxedCommand, buildInitialSandboxData, type SandboxData } from '../lib/sandbox.js';
import { parseJsonl } from './verify.js';
import {
  checkSmokeCoverage,
  extractSmokeIdsFromContent,
  type SmokeCoverageCheck,
  type SmokeCoverageDiagnostic,
} from '../lib/smoke-coverage.js';

const DEFAULT_SMOKE_RESULT_PATH = 'logos/resources/verify/smoke-results.jsonl';
const DEFAULT_SMOKE_REPORT_PATH = 'logos/resources/verify/smoke-report.md';
const SMOKE_CASES_DIR = 'logos/resources/test/smoke';

export interface SmokeData {
  environment: string | null;
  summary: {
    defined_count: number;
    executed_count: number;
    passed_count: number;
    failed_count: number;
    skipped_count: number;
    uncovered_count: number;
    coverage_pct: number;
    pass_rate_pct: number;
  };
  gate: {
    result: 'PASS' | 'FAIL';
    reason: string | null;
  };
  changed_cases: string[];
  diagnostics: SmokeCoverageDiagnostic[];
  runners: string[];
  failed_cases: Array<{ id: string; error: string }>;
  uncovered_cases: string[];
  skipped_cases: string[];
  sandbox: SandboxData;
  report_path: string;
  result_path: string;
}

export function extractSmokeDefinedIds(root: string): string[] {
  const dir = join(root, SMOKE_CASES_DIR);
  if (!existsSync(dir)) return [];

  const ids = new Set<string>();
  try {
    const files = readdirSync(dir, { recursive: true })
      .map(f => String(f))
      .filter(f => f.endsWith('.md'));

    for (const file of files) {
      const content = readFileSync(join(dir, file), 'utf-8');
      for (const id of extractSmokeIdsFromContent(content)) ids.add(id);
    }
  } catch { /* directory read error */ }

  return Array.from(ids).sort();
}

function readSmokeResults(root: string, resultPath: string) {
  const fullResultPath = join(root, resultPath);
  return existsSync(fullResultPath) ? parseJsonl(readFileSync(fullResultPath, 'utf-8')) : [];
}

function generateSmokeReport(data: SmokeData): string {
  const now = new Date().toISOString().slice(0, 10);
  let md = `# Smoke Report\n\n> Generated by \`openlogos smoke\` on ${now}\n`;
  if (data.environment) md += `> Environment: ${data.environment}\n`;
  md += '\n## Summary\n\n';
  md += '| Metric | Value |\n|--------|-------|\n';
  md += `| Defined cases | ${data.summary.defined_count} |\n`;
  md += `| Executed cases | ${data.summary.executed_count} |\n`;
  md += `| Passed | ${data.summary.passed_count} |\n`;
  md += `| Failed | ${data.summary.failed_count} |\n`;
  md += `| Skipped | ${data.summary.skipped_count} |\n`;
  md += `| Uncovered | ${data.summary.uncovered_count} |\n`;
  md += `| Coverage | ${data.summary.coverage_pct}% |\n`;
  md += `| Pass rate | ${data.summary.pass_rate_pct}% |\n`;
  md += `| **Gate 3.8** | **${data.gate.result}** |\n\n`;

  if (data.failed_cases.length > 0) {
    md += '## Failed Cases\n\n| ID | Error |\n|----|-------|\n';
    for (const item of data.failed_cases) {
      md += `| ${item.id} | ${item.error.replace(/\|/g, '\\|').replace(/\n/g, ' ')} |\n`;
    }
    md += '\n';
  }

  if (data.uncovered_cases.length > 0) {
    md += '## Uncovered Cases\n\n';
    for (const id of data.uncovered_cases) md += `- ${id}\n`;
    md += '\n';
  }

  if (data.diagnostics.length > 0) {
    md += '## Diagnostics\n\n| Code | Message | Cases |\n|------|---------|-------|\n';
    for (const item of data.diagnostics) {
      md += `| ${item.code} | ${item.message.replace(/\|/g, '\\|').replace(/\n/g, ' ')} | ${(item.case_ids ?? []).join(', ')} |\n`;
    }
    md += '\n';
  }

  if (data.skipped_cases.length > 0) {
    md += '## Skipped Cases\n\n';
    for (const id of data.skipped_cases) md += `- ${id}\n`;
    md += '\n';
  }

  return md;
}

export function collectSmokeData(
  root: string,
  environment?: string,
  sandbox?: SandboxData,
  coverageCheck?: SmokeCoverageCheck,
): SmokeData {
  const configPath = join(root, 'logos', 'logos.config.json');
  let resultPath = DEFAULT_SMOKE_RESULT_PATH;
  let reportPath = DEFAULT_SMOKE_REPORT_PATH;

  try {
    const config = JSON.parse(readFileSync(configPath, 'utf-8'));
    if (config.smoke?.result_path) resultPath = config.smoke.result_path;
    if (config.smoke?.report_path) reportPath = config.smoke.report_path;
  } catch { /* use defaults */ }

  const check = coverageCheck ?? checkSmokeCoverage(root, { resultPath });
  const results = readSmokeResults(root, resultPath);
  const defined = extractSmokeDefinedIds(root);
  const resultIds = new Set(results.map(r => r.id));
  const passed = results.filter(r => r.status === 'pass');
  const failed = results.filter(r => r.status === 'fail');
  const skipped = results.filter(r => r.status === 'skip');
  const uncovered = defined.filter(id => !resultIds.has(id));
  const coveredCount = defined.filter(id => resultIds.has(id)).length;

  const coveragePct = defined.length > 0 ? Math.round((coveredCount / defined.length) * 100) : 0;
  const passRatePct = results.length > 0 ? Math.round((passed.length / results.length) * 100) : 0;
  const isPass = failed.length === 0 && uncovered.length === 0 && check.diagnostics.length === 0;
  let reason: string | null = null;
  if (!isPass) {
    if (failed.length > 0) reason = 'failed_cases';
    else if (check.diagnostics.length > 0) reason = check.diagnostics[0].code;
    else reason = 'incomplete_coverage';
  }

  const data: SmokeData = {
    environment: environment ?? null,
    summary: {
      defined_count: defined.length,
      executed_count: results.length,
      passed_count: passed.length,
      failed_count: failed.length,
      skipped_count: skipped.length,
      uncovered_count: uncovered.length,
      coverage_pct: coveragePct,
      pass_rate_pct: passRatePct,
    },
    gate: {
      result: isPass ? 'PASS' : 'FAIL',
      reason,
    },
    changed_cases: check.changed_case_ids,
    diagnostics: check.diagnostics,
    runners: check.runners,
    failed_cases: failed.map(r => ({ id: r.id, error: r.error ?? 'unknown' })),
    uncovered_cases: uncovered,
    skipped_cases: skipped.map(r => r.id),
    sandbox: sandbox ?? buildInitialSandboxData(normalizeSandboxConfig({ sandbox_mode: 'auto' })),
    report_path: reportPath,
    result_path: resultPath,
  };

  const fullReportPath = join(root, reportPath);
  mkdirSync(dirname(fullReportPath), { recursive: true });
  writeFileSync(fullReportPath, generateSmokeReport(data));

  return data;
}

function readSmokeConfig(root: string): {
  command?: string;
  resultPath: string;
  reportPath: string;
  sandbox: ReturnType<typeof normalizeSandboxConfig>;
} {
  const configPath = join(root, 'logos', 'logos.config.json');
  let resultPath = DEFAULT_SMOKE_RESULT_PATH;
  let reportPath = DEFAULT_SMOKE_REPORT_PATH;
  let command: string | undefined;
  let sandbox = normalizeSandboxConfig({});
  try {
    const config = JSON.parse(readFileSync(configPath, 'utf-8'));
    if (config.smoke?.result_path) resultPath = config.smoke.result_path;
    if (config.smoke?.report_path) reportPath = config.smoke.report_path;
    if (config.smoke?.command) command = config.smoke.command;
    sandbox = normalizeSandboxConfig(config.smoke);
  } catch { /* use defaults */ }
  return { command, resultPath, reportPath, sandbox };
}

export function smoke(format: OutputFormat = 'text', environment?: string) {
  const root = process.cwd();
  const configPath = join(root, 'logos', 'logos.config.json');

  if (!existsSync(configPath)) {
    if (format === 'json') {
      console.error(JSON.stringify(makeErrorEnvelope(
        'smoke', 'PROJECT_NOT_INITIALIZED', 'logos/logos.config.json not found.',
      )));
      process.exit(1);
    }
    console.error('Error: logos/logos.config.json not found.');
    console.error('Run `openlogos init` first to initialize the project.');
    process.exit(1);
  }

  const locale = readLocale(root);
  const { command, resultPath, reportPath, sandbox } = readSmokeConfig(root);
  const allowedWritePaths = [resultPath, reportPath, 'logos/resources/verify/smoke-report.md'];
  let sandboxData = buildInitialSandboxData(sandbox);

  if (command) {
    if (format !== 'json') console.log(`\n⚙️  Running smoke.command: ${command}`);
    const result = runSandboxedCommand({
      root,
      command,
      format,
      sandbox,
      allowedWritePaths,
    });
    sandboxData = result.sandbox;
    if (result.command.status === 'fail') {
      if (format !== 'json') {
        console.warn('\n⚠️  smoke.command exited with non-zero status. Continuing smoke with existing results.');
      }
    }
  }

  const coverageCheck = checkSmokeCoverage(root, { command, resultPath });

  if (!existsSync(join(root, resultPath))) {
    if (coverageCheck.changed_case_ids.length > 0) {
      const data = collectSmokeData(root, environment, sandboxData, coverageCheck);
      if (format === 'json') {
        console.log(JSON.stringify(makeEnvelope('smoke', data)));
        process.exit(1);
      }
      console.error(`\nError: No smoke results found at ${resultPath}.`);
      for (const item of data.diagnostics) {
        console.error(`- ${item.code}: ${item.message}`);
      }
      process.exit(1);
    }
    if (format === 'json') {
      console.error(JSON.stringify(makeErrorEnvelope(
        'smoke', 'NO_SMOKE_RESULTS', `No smoke results found at ${resultPath}.`,
      )));
      process.exit(1);
    }
    console.error(`\nError: No smoke results found at ${resultPath}.`);
    process.exit(1);
  }

  const defined = extractSmokeDefinedIds(root);
  if (defined.length === 0) {
    if (format === 'json') {
      console.error(JSON.stringify(makeErrorEnvelope(
        'smoke', 'NO_SMOKE_CASES', 'No smoke case specs found in logos/resources/test/smoke/.',
      )));
      process.exit(1);
    }
    console.error('\nError: No smoke case specs found in logos/resources/test/smoke/.');
    process.exit(1);
  }

  const data = collectSmokeData(root, environment, sandboxData, coverageCheck);
  if (sandboxData.status === 'fail' && data.gate.result === 'PASS') {
    data.gate.result = 'FAIL';
    data.gate.reason = 'failed_cases';
    if (data.failed_cases.length === 0) {
      data.failed_cases.push({
        id: 'sandbox',
        error: sandboxData.diagnostics[0] ?? 'smoke sandbox failed',
      });
    }
  }

  const guardPath = join(root, 'logos', '.openlogos-guard');
  if (existsSync(guardPath)) {
    try {
      const guard = JSON.parse(readFileSync(guardPath, 'utf-8'));
      const slug = guard.activeChange;
      if (slug) {
        const proposalDir = join(root, 'logos', 'changes', slug);
        if (existsSync(proposalDir)) {
          if (data.gate.result === 'PASS') {
            writeFileSync(join(proposalDir, 'SMOKE_PASS'), '');
            const failPath = join(proposalDir, 'SMOKE_FAIL');
            if (existsSync(failPath)) rmSync(failPath, { force: true });
          } else {
            writeFileSync(join(proposalDir, 'SMOKE_FAIL'), '');
            const passPath = join(proposalDir, 'SMOKE_PASS');
            if (existsSync(passPath)) rmSync(passPath, { force: true });
          }
        }
      }
    } catch { /* guard 文件读取失败时静默跳过 */ }
  }

  if (format === 'json') {
    console.log(JSON.stringify(makeEnvelope('smoke', data)));
    if (data.gate.result !== 'PASS') process.exit(1);
    return;
  }

  console.log('\n🔎 OpenLogos Smoke Verification\n');
  if (data.environment) console.log(`  Environment: ${data.environment}`);
  console.log(`  Defined:  ${data.summary.defined_count}`);
  console.log(`  Executed: ${data.summary.executed_count}`);
  console.log(`  Passed:   ${data.summary.passed_count}`);
  console.log(`  Failed:   ${data.summary.failed_count}`);
  console.log(`  Skipped:  ${data.summary.skipped_count}`);
  console.log(`  Coverage: ${data.summary.coverage_pct}%`);
  console.log(`  Pass rate: ${data.summary.pass_rate_pct}%`);
  if (data.sandbox.mode !== 'off' || data.sandbox.status !== 'skipped') {
    console.log(`  ${t(locale, 'smoke.sandboxSummary', {
      mode: data.sandbox.mode,
      status: data.sandbox.status,
      isolated: String(data.sandbox.isolated),
      writeDenied: String(data.sandbox.workspace_write_denied),
    })}`);
    for (const line of data.sandbox.diagnostics) {
      console.log(`    - ${line}`);
    }
  }

  if (data.failed_cases.length > 0) {
    console.log('\nFailed smoke cases:');
    for (const item of data.failed_cases) console.log(`  ${item.id}  ${item.error}`);
  }

  if (data.uncovered_cases.length > 0) {
    console.log('\nUncovered smoke cases:');
    for (const id of data.uncovered_cases) console.log(`  ${id}`);
  }

  if (data.diagnostics.length > 0) {
    console.log('\nSmoke diagnostics:');
    for (const item of data.diagnostics) {
      const cases = item.case_ids?.length ? ` (${item.case_ids.join(', ')})` : '';
      console.log(`  ${item.code}${cases}: ${item.message}`);
    }
  }

  console.log(`\n${data.gate.result === 'PASS' ? '✅' : '❌'} Gate 3.8: ${data.gate.result}`);
  console.log(`\n📄 ${t(locale, 'verify.reportPath', { path: data.report_path })}\n`);

  if (data.gate.result !== 'PASS') process.exit(1);
}
